// ═══════════════════════════════════════════════════════════════
// codegen.js — Tạo code Lua (Roblox) và HTML Preview
// Phụ thuộc: definitions.js (DEFS, MDEF, COL, VERSION)
//            app.js          (els, getEl, getElRect, getChildren)
// ═══════════════════════════════════════════════════════════════

var etab = 'lua';

// ── HELPERS ─────────────────────────────────────────────────────
function _f(n)   { return parseFloat((n || 0).toFixed(4)); }
function _rgb(c) { return Math.round(c.r||0)+','+Math.round(c.g||0)+','+Math.round(c.b||0); }
function _hex2rgb(h) { return { r:parseInt(h.slice(1,3),16), g:parseInt(h.slice(3,5),16), b:parseInt(h.slice(5,7),16) }; }

/** Trả về danh sách elements theo thứ tự parent → children */
function _sorted() {
  var s = [];
  function add(el) { s.push(el); getChildren(el.id).forEach(add); }
  els.filter(function(e) { return !e.parentId; }).forEach(add);
  return s;
}

// ── EXPORT MODAL ────────────────────────────────────────────────
function setExTab(t) {
  etab = t;
  document.getElementById('etl').classList.toggle('on', t === 'lua');
  document.getElementById('eth').classList.toggle('on', t === 'html');
  document.getElementById('ec').textContent = t === 'lua' ? buildLua() : buildHTML();
}

function showExport() {
  var code = etab === 'lua' ? buildLua() : buildHTML();
  document.getElementById('ec').textContent = code;
  document.getElementById('einfo').textContent =
    els.length + ' elements · ' + code.split('\n').length + ' lines';
  document.getElementById('em').classList.add('show');
}

function hideExport() { document.getElementById('em').classList.remove('show'); }

function copyCode() {
  navigator.clipboard.writeText(etab === 'lua' ? buildLua() : buildHTML())
    .then(function() { toast('✅ Copied!'); });
}

function dlCode() {
  var code = etab === 'lua' ? buildLua() : buildHTML();
  var ext  = etab === 'lua' ? '.lua' : '.html';
  var a = document.createElement('a');
  a.href = URL.createObjectURL(new Blob([code], { type:'text/plain' }));
  a.download = 'roblox-ui' + ext;
  a.click();
}

// ════════════════════════════════════════════════════════════════
// BUILD LUA
// ════════════════════════════════════════════════════════════════
function buildLua() {
  var out = '-- Generated by Roblox UI Builder ' + VERSION + '\n'
          + 'local PlayerGui = game:GetService("Players").LocalPlayer:WaitForChild("PlayerGui")\n\n';

  _sorted().forEach(function(el, i) {
    var vn  = (el.name || el.type + i).replace(/\W/g, '_');
    var par = el.parentId
      ? (getEl(el.parentId).name || 'Frame').replace(/\W/g, '_')
      : 'PlayerGui';

    out += 'local ' + vn + ' = Instance.new("' + el.type + '")\n';
    out += vn + '.Name = "' + el.name + '"\n';
    out += vn + '.Parent = ' + par + '\n';

    // ── Thuộc tính chung (GuiObject) ──────────────────────────
    if (el.type !== 'ScreenGui' && el.type !== 'BillboardGui' &&
        el.type !== 'SurfaceGui' && el.type !== 'SelectionBox' &&
        el.type !== 'Highlight') {
      out += vn + '.Position = UDim2.new(' + _f(el.psX||0) + ',' + Math.round(el.poX||0)
           + ',' + _f(el.psY||0) + ',' + Math.round(el.poY||0) + ')\n';
      out += vn + '.Size = UDim2.new(' + _f(el.ssW||0) + ',' + Math.round(el.soW||0)
           + ',' + _f(el.ssH||0) + ',' + Math.round(el.soH||0) + ')\n';
      out += vn + '.AnchorPoint = Vector2.new(' + _f(el.ax||0) + ',' + _f(el.ay||0) + ')\n';
      out += vn + '.ZIndex = ' + (el.zi||0) + '\n';
      if (el.bc) out += vn + '.BackgroundColor3 = Color3.fromRGB(' + _rgb(el.bc) + ')\n';
      out += vn + '.BackgroundTransparency = ' + _f(1 - (el.op||1)) + '\n';
      if (el.vis === false) out += vn + '.Visible = false\n';
      if (el.rot) out += vn + '.Rotation = ' + _f(el.rot||0) + '\n';
    }

    if (el.warp) out += '-- ⚠ Warp trên ' + vn + ' không export được\n';

    // ── TextLabel / TextButton ─────────────────────────────────
    if (el.type === 'TextLabel' || el.type === 'TextButton') {
      out += vn + '.Text = "' + String(el.txt||'').replace(/"/g,'\\"') + '"\n';
      if (el.tc) out += vn + '.TextColor3 = Color3.fromRGB(' + _rgb(el.tc) + ')\n';
      out += vn + '.TextSize = ' + (el.tsz||14) + '\n';
      out += vn + '.Font = Enum.Font.' + (el.fn||'GothamMedium') + '\n';
      out += vn + '.TextXAlignment = Enum.TextXAlignment.' + (el.txa||'Left') + '\n';
      out += vn + '.TextYAlignment = Enum.TextYAlignment.' + (el.tya||'Center') + '\n';
      if (el.tw)  out += vn + '.TextWrapped = true\n';
      if (el.tsc) out += vn + '.TextScaled = true\n';
      if (el.rt)  out += vn + '.RichText = true\n';
    }

    // ── TextBox ───────────────────────────────────────────────
    if (el.type === 'TextBox') {
      out += vn + '.Text = "' + String(el.txt||'').replace(/"/g,'\\"') + '"\n';
      out += vn + '.PlaceholderText = "' + String(el.ph||'').replace(/"/g,'\\"') + '"\n';
      if (el.tc)  out += vn + '.TextColor3 = Color3.fromRGB(' + _rgb(el.tc) + ')\n';
      if (el.phc) out += vn + '.PlaceholderColor3 = Color3.fromRGB(' + _rgb(el.phc) + ')\n';
      out += vn + '.TextSize = ' + (el.tsz||14) + '\n';
      out += vn + '.Font = Enum.Font.' + (el.fn||'GothamMedium') + '\n';
      out += vn + '.TextXAlignment = Enum.TextXAlignment.' + (el.txa||'Left') + '\n';
      out += vn + '.TextYAlignment = Enum.TextYAlignment.' + (el.tya||'Center') + '\n';
      if (el.tw)        out += vn + '.TextWrapped = true\n';
      if (el.tsc)       out += vn + '.TextScaled = true\n';
      if (el.rt)        out += vn + '.RichText = true\n';
      if (el.cls)       out += vn + '.ClearTextOnFocus = true\n';
      if (el.multiLine) out += vn + '.MultiLine = true\n';
      if (el.maxLen > 0) out += vn + '.MaxVisibleGraphemes = ' + el.maxLen + '\n';
      out += '\n' + vn + '.FocusLost:Connect(function(enterPressed)\n\t-- TODO: handle input\nend)\n';
    }

    // ── ImageLabel / ImageButton ───────────────────────────────
    if (el.type === 'ImageLabel' || el.type === 'ImageButton') {
      if (el.img) out += vn + '.Image = "' + el.img + '"\n';
      if (el.ic)  out += vn + '.ImageColor3 = Color3.fromRGB(' + _rgb(el.ic) + ')\n';
      out += vn + '.ImageTransparency = ' + (el.it||0) + '\n';
      out += vn + '.ScaleType = Enum.ScaleType.' + (el.st||'Stretch') + '\n';
    }

    // ── ScrollingFrame ─────────────────────────────────────────
    if (el.type === 'ScrollingFrame') {
      out += vn + '.ScrollBarThickness = ' + (el.sbt||6) + '\n';
      if (el.sbc) out += vn + '.ScrollBarImageColor3 = Color3.fromRGB(' + _rgb(el.sbc) + ')\n';
      out += vn + '.CanvasSize = UDim2.new(0,0,0,' + (el.csy||200) + ')\n';
      if (el.se === false) out += vn + '.ScrollingEnabled = false\n';
    }

    // ── VideoFrame ─────────────────────────────────────────────
    if (el.type === 'VideoFrame') {
      out += vn + '.Video = "' + (el.vid||'rbxassetid://0') + '"\n';
      out += vn + '.Volume = ' + (el.vol||0.5) + '\n';
      if (el.vloop) out += vn + '.Looped = true\n';
      if (el.vplay) out += vn + ':Play()\n';
    }

    // ── ScreenGui ──────────────────────────────────────────────
    if (el.type === 'ScreenGui') {
      if (el.en === false) out += vn + '.Enabled = false\n';
      out += vn + '.DisplayOrder = ' + (el.dord||0) + '\n';
      if (el.ros === false) out += vn + '.ResetOnSpawn = false\n';
      if (el.igi) out += vn + '.IgnoreGuiInset = true\n';
    }

    // ── CanvasGroup ────────────────────────────────────────────
    if (el.type === 'CanvasGroup') {
      out += vn + '.GroupTransparency = ' + (el.gt||0) + '\n';
    }

    // ── Button shared ──────────────────────────────────────────
    if (el.type === 'TextButton' || el.type === 'ImageButton') {
      if (el.abc === false) out += vn + '.AutoButtonColor = false\n';
      if (el.modal) out += vn + '.Modal = true\n';
    }

    // ── BillboardGui ───────────────────────────────────────────
    if (el.type === 'BillboardGui') {
      var sz = el.sz || {x:4,y:2};
      out += vn + '.Size = UDim2.new(0,' + sz.x*50 + ',0,' + sz.y*50 + ') -- ' + sz.x + ' studs\n';
      var so = el.studOffset || {x:0,y:1,z:0};
      out += vn + '.StudsOffsetWorldSpace = Vector3.new(' + so.x + ',' + so.y + ',' + so.z + ')\n';
      if (el.alwaysOnTop) out += vn + '.AlwaysOnTop = true\n';
      if (el.lightInfluence !== undefined) out += vn + '.LightInfluence = ' + (el.lightInfluence||0) + '\n';
      if (el.maxDist > 0)  out += vn + '.MaxDistance = ' + el.maxDist + '\n';
      if (el.enabled === false) out += vn + '.Enabled = false\n';
      out += '-- ⚠ Gán Adornee thủ công: ' + vn + '.Adornee = workspace.YourPart\n';
    }

    // ── SurfaceGui ─────────────────────────────────────────────
    if (el.type === 'SurfaceGui') {
      out += vn + '.Face = Enum.NormalId.' + (el.face||'Front') + '\n';
      out += vn + '.PixelsPerStud = ' + (el.pixelsPerStud||50) + '\n';
      if (el.alwaysOnTop) out += vn + '.AlwaysOnTop = true\n';
      if (el.lightInfluence !== undefined) out += vn + '.LightInfluence = ' + (el.lightInfluence||0) + '\n';
      if (el.enabled === false) out += vn + '.Enabled = false\n';
      if (el.toolPunchThrough) out += vn + '.ToolPunchThroughDistance = 0\n';
      out += '-- ⚠ Gán Adornee thủ công: ' + vn + '.Adornee = workspace.YourPart\n';
    }

    // ── SelectionBox ───────────────────────────────────────────
    if (el.type === 'SelectionBox') {
      if (el.color) out += vn + '.Color3 = Color3.fromRGB(' + _rgb(el.color) + ')\n';
      out += vn + '.LineThickness = ' + (el.lineThickness||0.05) + '\n';
      if (el.surfaceColor) out += vn + '.SurfaceColor3 = Color3.fromRGB(' + _rgb(el.surfaceColor) + ')\n';
      out += vn + '.SurfaceTransparency = ' + (el.surfaceTransparency||0.7) + '\n';
      out += '-- ⚠ Gán Adornee thủ công: ' + vn + '.Adornee = workspace.YourPart\n';
    }

    // ── Highlight ──────────────────────────────────────────────
    if (el.type === 'Highlight') {
      if (el.fillColor)    out += vn + '.FillColor = Color3.fromRGB(' + _rgb(el.fillColor) + ')\n';
      out += vn + '.FillTransparency = ' + (el.fillTransparency||0.5) + '\n';
      if (el.outlineColor) out += vn + '.OutlineColor = Color3.fromRGB(' + _rgb(el.outlineColor) + ')\n';
      out += vn + '.OutlineTransparency = ' + (el.outlineTransparency||0) + '\n';
      out += vn + '.DepthMode = Enum.HighlightDepthMode.' + (el.depthMode||'AlwaysOnTop') + '\n';
      if (el.enabled === false) out += vn + '.Enabled = false\n';
      out += '-- ⚠ Gán Adornee thủ công: ' + vn + '.Adornee = workspace.YourPart\n';
    }

    // ── MODIFIERS ─────────────────────────────────────────────
    Object.keys(el.mods || {}).forEach(function(mk) {
      var md = el.mods[mk], mv = mk + '_' + vn;
      out += '\nlocal ' + mv + ' = Instance.new("' + mk + '")\n';
      out += mv + '.Parent = ' + vn + '\n';

      if (mk === 'UICorner')
        out += mv + '.CornerRadius = UDim.new(0,' + (md.cr||0) + ')\n';

      if (mk === 'UIGradient') {
        var c0 = _hex2rgb(md.c0||'#7c6af7'), c1 = _hex2rgb(md.c1||'#22d3ee');
        // Multi-stop support
        if (md.stops && md.stops.trim()) {
          try {
            var stops = md.stops.split(',').map(function(s) {
              var parts = s.trim().split('=');
              return { t: parseFloat(parts[0]), col: _hex2rgb(parts[1]||'#ffffff') };
            });
            var kps = stops.map(function(s) {
              return 'ColorSequenceKeypoint.new(' + s.t + ',Color3.fromRGB(' + _rgb(s.col) + '))';
            }).join(',\n\t\t');
            out += mv + '.Color = ColorSequence.new({\n\t\t' + kps + '\n\t})\n';
          } catch(e) {
            out += mv + '.Color = ColorSequence.new({ColorSequenceKeypoint.new(0,Color3.fromRGB('
                 + _rgb(c0) + ')),ColorSequenceKeypoint.new(1,Color3.fromRGB(' + _rgb(c1) + '))})\n';
          }
        } else {
          out += mv + '.Color = ColorSequence.new({ColorSequenceKeypoint.new(0,Color3.fromRGB('
               + _rgb(c0) + ')),ColorSequenceKeypoint.new(1,Color3.fromRGB(' + _rgb(c1) + '))})\n';
        }
        out += mv + '.Rotation = ' + (md.rot||0) + '\n';
        if (md.en === false) out += mv + '.Enabled = false\n';
      }

      if (mk === 'UIStroke') {
        var sc = _hex2rgb(md.col||'#7c6af7');
        out += mv + '.Color = Color3.fromRGB(' + _rgb(sc) + ')\n';
        out += mv + '.Thickness = ' + (md.th||2) + '\n';
        out += mv + '.Transparency = ' + (md.tr||0) + '\n';
        if (md.applyStrokeMode) out += mv + '.ApplyStrokeMode = Enum.ApplyStrokeMode.' + md.applyStrokeMode + '\n';
        if (md.en === false) out += mv + '.Enabled = false\n';
      }

      if (mk === 'UIPadding')
        out += mv + '.PaddingTop = UDim.new(0,' + (md.t||0) + ')\n'
             + mv + '.PaddingBottom = UDim.new(0,' + (md.b||0) + ')\n'
             + mv + '.PaddingLeft = UDim.new(0,' + (md.l||0) + ')\n'
             + mv + '.PaddingRight = UDim.new(0,' + (md.r||0) + ')\n';

      if (mk === 'UIScale')
        out += mv + '.Scale = ' + (md.sc||1) + '\n';

      if (mk === 'UIAspectRatioConstraint')
        out += mv + '.AspectRatio = ' + (md.ar||1) + '\n'
             + mv + '.AspectType = Enum.AspectType.' + (md.at||'FitWithinMaxSize') + '\n'
             + mv + '.DominantAxis = Enum.DominantAxis.' + (md.da||'Width') + '\n';

      if (mk === 'UISizeConstraint')
        out += mv + '.MinSize = Vector2.new(' + (md.mnx||0) + ',' + (md.mny||0) + ')\n'
             + mv + '.MaxSize = Vector2.new(' + (md.mxx||999) + ',' + (md.mxy||999) + ')\n';

      if (mk === 'UITextSizeConstraint')
        out += mv + '.MinTextSize = ' + (md.mn||6) + '\n'
             + mv + '.MaxTextSize = ' + (md.mx||100) + '\n';

      if (mk === 'UIListLayout')
        out += mv + '.FillDirection = Enum.FillDirection.' + (md.fd||'Vertical') + '\n'
             + mv + '.HorizontalAlignment = Enum.HorizontalAlignment.' + (md.ha||'Left') + '\n'
             + mv + '.VerticalAlignment = Enum.VerticalAlignment.' + (md.va||'Top') + '\n'
             + mv + '.SortOrder = Enum.SortOrder.' + (md.so||'LayoutOrder') + '\n'
             + mv + '.Padding = UDim.new(0,' + (md.pd||0) + ')\n'
             + (md.wr ? mv + '.Wraps = true\n' : '');

      if (mk === 'UIGridLayout')
        out += mv + '.CellSize = UDim2.new(0,' + (md.cs||100) + ',0,' + (md.cs||100) + ')\n'
             + mv + '.CellPadding = UDim2.new(0,' + (md.cpx||4) + ',0,' + (md.cpy||4) + ')\n'
             + mv + '.FillDirection = Enum.FillDirection.' + (md.fd||'Horizontal') + '\n'
             + mv + '.SortOrder = Enum.SortOrder.' + (md.so||'LayoutOrder') + '\n';

      if (mk === 'UITableLayout')
        out += mv + '.FillEmptySpaceColumns = ' + (md.fec?'true':'false') + '\n'
             + mv + '.FillEmptySpaceRows = ' + (md.fer?'true':'false') + '\n';

      if (mk === 'UIPageLayout')
        out += mv + '.Animated = ' + (md.an!==false?'true':'false') + '\n'
             + mv + '.AnimationDirection = Enum.AnimationDirection.' + (md.ad||'Horizontal') + '\n'
             + mv + '.Circular = ' + (md.ci?'true':'false') + '\n';

      if (mk === 'UIFlexItem')
        out += mv + '.FlexMode = Enum.UIFlexMode.' + (md.fm||'Fill') + '\n'
             + mv + '.GrowRatio = ' + (md.gr||1) + '\n'
             + mv + '.ShrinkRatio = ' + (md.sr||1) + '\n';

      // Effects
      if (mk === 'UIBlurEffect')
        out += mv + '.Size = ' + (md.size||24) + '\n'
             + (md.en===false ? mv + '.Enabled = false\n' : '');

      if (mk === 'UIColorCorrectionEffect')
        out += mv + '.Brightness = ' + (md.brightness||0) + '\n'
             + mv + '.Contrast = ' + (md.contrast||0) + '\n'
             + mv + '.Saturation = ' + (md.saturation||0) + '\n'
             + (md.tintColor ? mv + '.TintColor = Color3.fromRGB(' + _rgb(md.tintColor) + ')\n' : '')
             + (md.en===false ? mv + '.Enabled = false\n' : '');

      if (mk === 'UIBloomEffect')
        out += mv + '.Intensity = ' + (md.intensity||0.8) + '\n'
             + mv + '.Size = ' + (md.size||24) + '\n'
             + mv + '.Threshold = ' + (md.threshold||0.95) + '\n'
             + (md.en===false ? mv + '.Enabled = false\n' : '');

      if (mk === 'UIDepthOfFieldEffect')
        out += mv + '.FarIntensity = ' + (md.farIntensity||0) + '\n'
             + mv + '.FocusDistance = ' + (md.focusDistance||50) + '\n'
             + mv + '.InFocusRadius = ' + (md.inFocusRadius||10) + '\n'
             + mv + '.NearIntensity = ' + (md.nearIntensity||0) + '\n'
             + (md.en===false ? mv + '.Enabled = false\n' : '');

      if (mk === 'UISunRaysEffect')
        out += mv + '.Intensity = ' + (md.intensity||0.25) + '\n'
             + mv + '.Spread = ' + (md.spread||1) + '\n'
             + (md.en===false ? mv + '.Enabled = false\n' : '');
    });

    // ── Click handler cho Button ───────────────────────────────
    if (el.type === 'TextButton' || el.type === 'ImageButton')
      out += '\n' + vn + '.MouseButton1Click:Connect(function()\n\t-- TODO\nend)\n';

    out += '\n';
  });

  return out;
}

// ════════════════════════════════════════════════════════════════
// BUILD HTML PREVIEW
// ════════════════════════════════════════════════════════════════
function buildHTML() {
  var out = '<!DOCTYPE html>\n<html>\n<head>\n<meta charset="UTF-8">\n'
          + '<style>body{margin:0;background:#0d0d14}.ui{position:relative;width:800px;height:600px}</style>\n'
          + '</head>\n<body>\n<div class="ui">\n';

  _sorted().forEach(function(el) {
    // Các type 3D không render HTML
    if (['ScreenGui','BillboardGui','SurfaceGui','SelectionBox','Highlight'].includes(el.type)) return;

    var r  = getElRect(el);
    var bg = el.bc ? 'rgb(' + _rgb(el.bc) + ')' : '#222';
    var m  = el.mods || {};

    var st = 'position:absolute;left:' + Math.round(r.x) + 'px;top:' + Math.round(r.y) + 'px;'
           + 'width:' + Math.round(r.w) + 'px;height:' + Math.round(r.h) + 'px;'
           + 'opacity:' + (el.op||1) + ';z-index:' + (el.zi||0) + ';';

    if (r.rot) st += 'transform:rotate(' + r.rot + 'deg);transform-origin:center;';
    if (m.UICorner) st += 'border-radius:' + (m.UICorner.cr||0) + 'px;';
    if (m.UIGradient && m.UIGradient.en !== false)
      st += 'background:linear-gradient(' + (m.UIGradient.rot||0) + 'deg,' + m.UIGradient.c0 + ',' + m.UIGradient.c1 + ');';
    else
      st += 'background:' + bg + ';';
    if (m.UIStroke && m.UIStroke.en !== false)
      st += 'outline:' + (m.UIStroke.th||2) + 'px solid ' + (m.UIStroke.col||'#7c6af7') + ';';
    if (m.UIPadding)
      st += 'padding:' + (m.UIPadding.t||0) + 'px ' + (m.UIPadding.r||0) + 'px '
          + (m.UIPadding.b||0) + 'px ' + (m.UIPadding.l||0) + 'px;';
    if (m.UIBlurEffect)
      st += 'filter:blur(' + Math.round((m.UIBlurEffect.size||24)/8) + 'px);';

    if (el.warp) {
      var w = el.warp, W = r.w, H = r.h;
      var pts = [[w.tl.x,w.tl.y],[W+w.tr.x,w.tr.y],[W+w.br.x,H+w.br.y],[w.bl.x,H+w.bl.y]]
        .map(function(p) { return (p[0]/W*100).toFixed(1)+'% '+(p[1]/H*100).toFixed(1)+'%'; });
      st += 'clip-path:polygon(' + pts.join(',') + ');';
    }

    // Text elements
    if (el.type === 'TextLabel' || el.type === 'TextButton' || el.type === 'TextBox') {
      var tc = el.tc ? 'rgb(' + _rgb(el.tc) + ')' : '#fff';
      var jc = el.txa === 'Center' ? 'center' : el.txa === 'Right' ? 'flex-end' : 'flex-start';
      st += 'display:flex;align-items:center;justify-content:' + jc + ';color:' + tc
          + ';font-size:' + (el.tsz||14) + 'px;font-weight:' + (el.type==='TextButton'?700:400)
          + ';padding:0 7px;' + (el.type==='TextButton'?'cursor:pointer;':'');
      var display = el.type === 'TextBox'
        ? '<input type="text" placeholder="' + (el.ph||'') + '" value="' + (el.txt||'')
          + '" style="background:none;border:none;outline:none;color:inherit;font-size:inherit;width:100%">'
        : (el.txt || '');
      out += '  <div style="' + st + '">' + display + '</div>\n';
    } else {
      out += '  <div style="' + st + '"></div>\n';
    }
  });

  out += '</div>\n</body>\n</html>';
  return out;
}
